Vertical Candidate List=False
WheelForPaging=True
Font="Noto Sans CJK SC 13"
MenuFont="Noto Sans CJK SC 13"
TrayFont="Sans Bold 13"
TrayOutlineColor=#302f2c
TrayTextColor=#f2f2f2
PreferTextIcon=False
ShowLayoutNameInIcon=True
UseInputMethodLanguageToDisplayText=True
Theme=bamboo-dark
DarkTheme=bamboo-dark
UseDarkTheme=False
UseAccentColor=True
PerScreenDPI=False
ForceWaylandDPI=0
EnableFractionalScale=True

