Vertical Candidate List=False
WheelForPaging=True
Font="JetBrainsMono Nerd Font 13"
MenuFont="JetBrainsMono Nerd Font 13"
TrayFont="Sans Bold 13"
TrayOutlineColor=#302f2c
TrayTextColor=#f2f2f2
PreferTextIcon=False
ShowLayoutNameInIcon=True
UseInputMethodLanguageToDisplayText=True
Theme=omarchy
DarkTheme=omarchy
UseDarkTheme=False
UseAccentColor=True
PerScreenDPI=False
ForceWaylandDPI=0
EnableFractionalScale=True

